name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.92.0"
          components: rustfmt

      - run: make fmt

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libclang-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.92.0"

      - uses: Swatinem/rust-cache@v2

      - run: make test.unit
